### ISSUE TITLE
joern-parse produces wrong node and edge files

### ISSUE THREAD

**Issue by dmc1778** [saikat107/C-Code-Slicer#2]
When I want to use the library to produce nodes and edges files on some C code snippets, the python `parse_joern_output.py` throws `KeyError`.

My code snippet is:

``
static void short_pinky (const char *filename, const int argc_names, char * const argv_names []) {
    size_t n_users;
    STRUCT_UTMP *utmp_buf = NULL;
    if (read_utmp (filename, &n_users, &utmp_buf, 0) != 0)
        die (EXIT_FAILURE, errno, "%s", quotef (filename));
    scan_entries (n_users, utmp_buf, argc_names, argv_names);
    IF_LINT (free (utmp_buf));
}
``

**Comment by saikat107** [comment]
Apparently, `joern` fails to parse the code snippet you provided. 
Updated the code with an early exit (see 9e7e6c9bc7fcff7010e9911788ea15e11522d586) for such a case.

Feel free to create a Pull Request if you are able to solve this problem.
